name = "quiet-the-mowers"
compatibility_date = "2026-04-29"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "qtm-db"
database_id = "qtm-db-dev"

[[kv_namespaces]]
binding = "SESSION"
id = "session-dev"
